if(MIRA_ENABLE_TSAN AND (MIRA_ENABLE_ASAN OR MIRA_ENABLE_UBSAN))
    message(FATAL_ERROR "ThreadSanitizer cannot be combined with ASAN/UBSAN")
endif()

function(mira_enable_sanitizers target)
    if(NOT CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
        if(MIRA_ENABLE_ASAN OR MIRA_ENABLE_UBSAN OR MIRA_ENABLE_TSAN)
            message(FATAL_ERROR "Requested sanitizer requires GCC or Clang")
        endif()
        return()
    endif()

    if(MIRA_ENABLE_ASAN)
        target_compile_options(${target} PRIVATE -fsanitize=address -fno-omit-frame-pointer)
        target_link_options(${target} PRIVATE -fsanitize=address)
    endif()
    if(MIRA_ENABLE_UBSAN)
        target_compile_options(${target} PRIVATE -fsanitize=undefined -fno-omit-frame-pointer)
        target_link_options(${target} PRIVATE -fsanitize=undefined)
    endif()
    if(MIRA_ENABLE_TSAN)
        target_compile_options(${target} PRIVATE -fsanitize=thread -fno-omit-frame-pointer)
        target_link_options(${target} PRIVATE -fsanitize=thread)
    endif()
endfunction()
